image: docker

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

variables:
  OSM_DIR: /data/osm
  ADDR_DIR: /data/addresses
  COSMOGONY_DIR: /data/cosmogony

test:
  before_script:
   - apk add --no-cache python3 py3-pip git bash
   - pip3 install docker-compose pipenv
   - git clone -b dockerfile https://github.com/antoine-de/geocoder-tester.git
   - cd geocoder-tester
   - docker build -t geocoder-tester .
   - cd ..
   - docker build -t mimirsbrunn -f docker/Dockerfile_import .
   - docker build -t bragi -f docker/Dockerfile_bragi .
   - git clone -b docker-compose https://github.com/QwantResearch/docker_mimir.git
   - mv tester_settings.yml docker_mimir/
   - cd docker_mimir
   - pipenv install --system --deploy
   - mkdir -p /data/osm
   - wget https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf -P /data/osm
  script:
   - inv -f tester_settings.yaml load-in-docker-and-test
  artifacts:
    expire_in: 2 weeks
    paths:
      - results
