image: docker

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

test:
  before_script:
   - apk add --no-cache python3 py3-pip
   - pip3 install docker-compose pipenv
   - git clone -b docker-compose https://github.com/QwantResearch/docker_mimir.git
   - cd docker_mimir
   - pipenv install --system --deploy
   - docker-compose build
   - mkdir -p /data/osm
   - wget https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf -P /data/osm
  script:
   - inv -f docker_settings.yaml load-in-docker-and-test
