image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SHARED_PATH: /builds/$CI_PROJECT_PATH/shared

test:
  before_script:
   - export OSM_DIR=$SHARED_PATH/data/osm ADDR_DIR=$SHARED_PATH/data/addresses COSMOGONY_DIR=$SHARED_PATH/data/cosmogony
   - apk add --no-cache python3 py3-pip git bash
   - pip3 install docker-compose pipenv
   - git clone -b dockerfile https://github.com/antoine-de/geocoder-tester.git
   - cd geocoder-tester
   - docker build -t geocoder-tester .
   - cd ..
   - docker build -t mimirsbrunn -f docker/Dockerfile_import .
   - docker build -t bragi -f docker/Dockerfile_bragi .
   - git clone -b docker-compose https://github.com/QwantResearch/docker_mimir.git
   - mv tester_settings.yml docker_mimir/
   - cd docker_mimir
   - pipenv install --system --deploy
   - mkdir -p $OSM_DIR
   - wget https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf -P $OSM_DIR
  script:
   - docker-compose run mimir ls -l /data/osm
   - inv -f tester_settings.yml load-in-docker-and-test
  artifacts:
    expire_in: 2 weeks
    paths:
      - results
