# example file to run mimir in docker, the file path must be changed
osm_file: /data/osm/luxembourg-latest.osm.pbf
es: http://es:9200

admin:
  cosmogony:
    output_dir: /data/cosmogony

poi:
  osm:


# TODO: import addresses
# addresses:
#   oa_file: /data/addresses/luxembourg.csv
