image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SHARED_PATH: /builds/$CI_PROJECT_PATH/shared

geocoder-tester:
  before_script:
   - export OSM_DIR=$SHARED_PATH/data/osm ADDR_DIR=$SHARED_PATH/data/addresses
   - apk add --no-cache python3 py3-pip git bash
   - pip3 install docker-compose pipenv
   - git clone -b esTimeout https://github.com/QwantResearch/docker_mimir.git
   - mv ci/gitlab/*.yml docker_mimir/
   - cd docker_mimir
   - pipenv install --system --deploy
   - ../ci/gitlab/download_data.sh
  script:
   - inv -f import_settings_with_cosmogony.yml load-in-docker-and-test --files docker-compose.build.yml
  artifacts:
    expire_in: 2 weeks
    paths:
      - docker_mimir/results
