image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SHARED_PATH: /builds/$CI_PROJECT_PATH/shared

cache:
  key: ${CI_PROJECT_PATH}_data
  paths:
    - shared/

geocoder-tester-cosmogony:
  before_script:
    - export OSM_DIR=$SHARED_PATH/osm ADDR_DIR=$SHARED_PATH/addresses
    - ls -Rlh $SHARED_PATH
    - apk add --no-cache python3 py3-pip git bash
    - ./ci/gitlab/init.sh
    - ./ci/gitlab/download_data.sh
  script:
    - cd docker_mimir
    - inv -f import_settings_with_cosmogony.yml load-in-docker-and-test --files docker-compose.build.yml
  artifacts:
    expire_in: 2 weeks
    paths:
      - docker_mimir/results
  tags:
    - geocoder-tester
  only:
    - web


# geocoder-tester-osm-admins:
#   before_script:
#     - export OSM_DIR=$SHARED_PATH/data/osm ADDR_DIR=$SHARED_PATH/data/addresses
#     - apk add --no-cache python3 py3-pip git bash
#     - ./ci/gitlab/init.sh
#     - ./ci/gitlab/download_data.sh
#   script:
#     - cd docker_mimir
#     - inv -f import_settings_without_cosmogony.yml load-in-docker-and-test --files docker-compose.build.yml
#   artifacts:
#     expire_in: 2 weeks
#     paths:
#       - docker_mimir/results
#   tags:
#     - france_osm_admins


