# example file to run mimir in docker, the file path must be changed
es: http://es:9200

osm_file: /data/osm/france-latest.osm.pbf

admin:
  cosmogony:
    output_dir: /data/cosmogony

poi:
  osm:

addresses:
  bano_file: /data/addresses/full.csv
